apiVersion: v1
kind: Pod
metadata:
  name: kaniko-pod-${HASH}
  namespace: sys-gitlab
spec:
  containers:
    - name: kaniko-${HASH}
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--destination=${DESTINATION}"
        - "--destination=${DESTINATION_LATEST}"
        - "--context=${CONTEXT}"
        - "--context-sub-path=${CONTEXT_PATH}"
        - "--dockerfile=${DOCKERFILE}"
      volumeMounts:
        - name: kaniko-${HASH}
          mountPath: "/kaniko/.docker/config.json"
          subPath: config.json
  restartPolicy: Never
  volumes:
    - name: kaniko-${HASH}
      secret:
        secretName: kaniko-${HASH}
