name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: build
        run: |
          VERSION=$(git describe | awk -F '-' '{print $1}')
          docker login registry.hub.docker.com -u "${{ secrets.DOCKER_HUB_USERNAME }}" -p "${{ secrets.DOCKER_HUB_PASSWORD }}"
          docker build -f ./Dockerfile -t registry.hub.docker.com/lukaspastva/gitlab-runner:latest .
          docker tag registry.hub.docker.com/lukaspastva/gitlab-runner:latest registry.hub.docker.com/lukaspastva/gitlab-runner:${VERSION}
          docker push registry.hub.docker.com/lukaspastva/gitlab-runner:latest
          docker push registry.hub.docker.com/lukaspastva/gitlab-runner:${VERSION}
